import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1766391890493 implements MigrationInterface {
    name = 'InitSchema1766391890493'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_activities_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_news_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_patients_email"`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "subject"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "subject" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "message" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."message_status" RENAME TO "message_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."contact_message_status_enum" AS ENUM('UNREAD', 'READ', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" TYPE "public"."contact_message_status_enum" USING "status"::"text"::"public"."contact_message_status_enum"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" SET DEFAULT 'UNREAD'`);
        await queryRunner.query(`DROP TYPE "public"."message_status_old"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "title" character varying`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "specialty"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "specialty" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "degrees" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "experience"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "experience" character varying`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "photo"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "photo" character varying`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "bio" character varying`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "doctors_email_key"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "UQ_62069f52ebba471c91de5d59d61" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "image" character varying`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" ALTER COLUMN "date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "patients_email_key"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "UQ_64e2031265399f5690b0beba6a5" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "birthDate" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "photo"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "photo" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "photo"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "photo" text`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "phone" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "birthDate" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "UQ_64e2031265399f5690b0beba6a5"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "patients_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "fullName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "news" ALTER COLUMN "date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "image" text`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "UQ_62069f52ebba471c91de5d59d61"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "doctors_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "photo"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "photo" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "experience"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "experience" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "degrees" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "specialty"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "specialty" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "title" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."message_status_old" AS ENUM('UNREAD', 'READ', 'ARCHIVED')`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" TYPE "public"."message_status_old" USING "status"::"text"::"public"."message_status_old"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ALTER COLUMN "status" SET DEFAULT 'UNREAD'`);
        await queryRunner.query(`DROP TYPE "public"."contact_message_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."message_status_old" RENAME TO "message_status"`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "message" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "subject"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "subject" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "phone" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contact_message" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "contact_message" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_patients_email" ON "patients" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_patients_created_at" ON "patients" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_news_created_at" ON "news" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_activities_created_at" ON "activities" ("createdAt") `);
    }

}
